apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: build-with-oc
spec:
  source:
    git:
      url: https://github.com/arijknani/containerized-app
      ref: build-with-oc
    type: Git
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  output:
    image: docker.io/arijknani009/example:latest
