apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  generation: 1
  labels:
    app: springboot-app
    app.kubernetes.io/component: springboot-app
    app.kubernetes.io/instance: springboot-app
  name: springboot-app
  namespace: arij-project
spec:
  output:
    to:
      kind: ImageStreamTag
      name: springboot-app:latest
  runPolicy: Serial
  source:
    git:
      ref: build-with-oc
      uri: https://github.com/arijknani/containerized-app.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk:latest
        namespace: arij-project
    type: Docker
  triggers:
  - github:
      secret: 5HBvJzxW8POqJ6KHeOrh
    type: GitHub
  - generic:
      secret: QxdAcouKfjiCUOJ2_k-1
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
